config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
    validates :name, presence: true
    validates :address, presence: true
    validates :description, presence: true
    validates :price_per_night, presence: true
    validates :number_of_guest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
    before_action :find_flat, only: [:edit, :show, :update, :destroy]

    def index()
        if params[:query].present?
            @query = params[:query]
            @flats = Flat.where("name LIKE '%#{params[:query]}%'")
        else 
            @flats = Flat.all
        end
    end

    def create()
        @flat = Flat.new(flat_params)

        if @flat.save
            redirect_to flat_path(@flat)
        else 
            render :new
        end
    end

    def new()
        @flat = Flat.new
    end

    def edit()
    end

    def show()
    end

    def update()
        if @flat.update(flat_params)
            redirect_to flat_path(@flat)
        else
            render :edit
        end
    end

    def destroy()
        @flat.destroy
        @flat.save
        redirect_to flats_path
    end

    private

    def flat_params()
        params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guest)
    end

    def find_flat()
        @flat = Flat.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
  <%= simple_form_for @flat do |f|  %>
  <%= f.input :name  %>
  <%= f.input :address  %>
  <%= f.input :description  %>
  <%= f.input :price_per_night  %>
  <%= f.input :number_of_guest  %>
  <%= f.submit class: "btn btn-primary"  %>
  <%= link_to "Cancel", flats_path, class:"btn btn-danger" %>
  <% end %>

app/views/flats/edit.html.erb
<div class="container mt-3">
  <%= render 'form', flat: @flat  %>
</div>

app/views/flats/index.html.erb
<div class="container">
    <div class="index-header">

        <% if @query %>

        <h1 class="index-title"><strong>All of our Flats</strong></h1>
        <p>you searched for <%= @query %>. We found <%= @flats.count%> out of <%= Flat.count  %> on our website</p>
        <% else %>
        <h1 class="index-title"><strong>All Flats</strong></h1>
        <p>All <%=  @number_of_flats %> flats.</p>
        <% end %>
    </div>


  <div class="card-product-infos">
    <% @flats.each do |flat| %>
        <div class="card-content">
            <div class="card-img">
            <% if flat.photo_url.present? %>
                 <%= image_tag flat.photo_url%>
                <% else %>
                   <img src="https://source.unsplash.com/collection/190727/1600x900" height="50px" width="50px" alt="">
            <% end %>

            </div>
            <div class="card-body">
                <div class="card-content-title">
                    <h1><%=  flat.name %></h1>
                </div>
                <div class="card-content-address">
                    <p><%=  flat.address %></p>
                </div>
                <div class="card-flat-info">
                    <div class="card-guest">
                        <i class="fas fa-user-friends"></i>
                        <span><%=  flat.number_of_guest %></span>
                    </div>
                    <div class="card-price">
                        <i class="fas fa-euro-sign"></i>
                        <span><%=  flat.price_per_night %></span>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <%= link_to "More info", flat_path(flat) %>
                <%= link_to "Edit", edit_flat_path(flat), class: "card-edit-link" %>
                <%= link_to "Delete",
                flat_path(flat),
                class: "card-delete-link",
                method: :delete,
                data: { confirm: "Are you sure you want to delete #{flat.name}?" }
                %>
            </div>
        </div>
    <% end %>
    </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-3">
  <%= render 'form', flat: @flat %>
</div>

app/views/flats/show.html.erb
<% if @flat.photo_url.present? %>
    <div class="map" style="background-image: 
        url(' <%= @flat.photo_url  %>')">
    </div>
    <% else %>
 <div class="map" style="background-image: 
        url(' https://source.unsplash.com/collection/190727/1600x900')">
    </div>
<% end %>

<div class="container">
    <div class="row">
        <div class="col-8">
            <div class="flat-show-card">
                <div class="flat-show-card-content">
                    <h1><%= @flat.name  %></h1>
                    <p><%= @flat.address%></p>
                </div>
            </div>
            <div class="flat-show-card" id="show-card-description">
                <div class="flat-show-card-content">
                    <h1><%= @flat.name  %></h1>
                    <p><%= @flat.description%></p>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="flat-show-card" id="flat-show-book">
                <h1>Book This Place</h1>
                <form action="">
                    <div class="input-group" id="flat-show-input">
                        <span class="input-group-addon" id="basic-addon1">From:</span>
                        <input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username" aria-describedby="basic-addon1">
                    </div>
                    <div class="input-group mt-2" id="flat-show-input" >
                        <span class="input-group-addon" id="basic-addon1">To:</span>
                         <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
                    </div>
                    <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
                </form>           
             </div>
            <div class="flat-show-card" id="flat-show-detail">
                <h1>Details</h1>
                <div class="card-detail d-flex">
                    <div class="card-guest">
                        <i class="fas fa-user-friends"></i>
                        <span><%=  @flat.number_of_guest %></span>
                    </div>
                    <div class="card-price">
                        <i class="fas fa-euro-sign"></i>
                        <span><%=  @flat.price_per_night %></span>
                    </div>
                </div>
            </div>
            <div class="flat-show-card" id="show-card-share">
                <div class="card-share-title">
                    <h6>Share</h6> 
                </div>
                <div class="card-share-links">
                    <i class="fab fa-facebook"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-instagram"></i>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to flats_path, class: "navbar-brand" do %> Simple Airbnb
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
       <% if current_page?(flats_path)%>
        <form class="form-inline my-2 pr-2 my-lg-0">
          <input id="nav-input-btn" class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value=""<%= params[:query] %>">
          <button id="nav-search-btn" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <% end %>
      </li>
      <li class="nav-item pr-1">
        <%= link_to "Add Flat", new_flat_path, class: "btn btn-primary", id:"nav-add-btn" %>
      </li>
    </ul>
  </div>
</div>


    <%= yield %>
  </body>
</html>